### PR TITLE
*: Prepare v0.12.1

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by mxinden** [comment]
[Tagged](https://github.com/mxinden/rust-open-metrics-client/releases/tag/v0.12.1) and [published](https://crates.io/crates/open-metrics-client/0.12.1).

//CC @divagant-martian

**Comment by mxinden** [comment]
I yanked the release due to https://github.com/libp2p/rust-libp2p/issues/2333#issuecomment-964668411. I will most likely cut a new release (`v0.13.0`) tomorrow.

**Comment by divagant-martian** [comment]
I'm surprised about this error since there is a test with that specific function. I'll look into it

**Comment by divagant-martian** [comment]
So it looks like the type inference breaks. The failing lines are fixed by specifying the types. I don't see an alternative and thus would make it a breaking change indeed

**Pull request merged**
